USE [master]
GO

CREATE DATABASE [PC4Customers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PC4Customers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PC4Customers.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PC4Customers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PC4Customers_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PC4Customers] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PC4Customers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PC4Customers] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PC4Customers] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PC4Customers] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PC4Customers] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PC4Customers] SET ARITHABORT OFF 
GO
ALTER DATABASE [PC4Customers] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PC4Customers] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PC4Customers] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PC4Customers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PC4Customers] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PC4Customers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PC4Customers] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PC4Customers] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PC4Customers] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PC4Customers] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PC4Customers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PC4Customers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PC4Customers] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PC4Customers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PC4Customers] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PC4Customers] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PC4Customers] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PC4Customers] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PC4Customers] SET  MULTI_USER 
GO
ALTER DATABASE [PC4Customers] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PC4Customers] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PC4Customers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PC4Customers] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PC4Customers] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PC4Customers] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PC4Customers] SET QUERY_STORE = OFF
GO
USE [PC4Customers]
GO
/****** Object:  Table [dbo].[Customers] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Address] [nvarchar](50) NULL,
	[City] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL,
	[PostalCode] [nvarchar](50) NULL,
	[Phone] [nvarchar](50) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PC4Customers] SET  READ_WRITE 
GO
